export const dummyShowsData = [
  {
    _id: "1",
    title: "Now You See Me",
    backdrop_path: "/now-you-see-me-3.jpg",
    release_date: "2013-05-31",
    genres: [{ name: "Thriller" }, { name: "Mystery" }],
    runtime: "115",
    vote_average: 7.3,
  },
  {
    _id: "2",
    title: "Inception",
    backdrop_path: "/inception.jpg",
    release_date: "2010-07-16",
    genres: [{ name: "Sci-Fi" }, { name: "Action" }],
    runtime: "148",
    vote_average: 8.8,
  },
  {
    _id: "3",
    title: "The Dark Knight",
    backdrop_path: "/the-dark-knight.jpg",
    release_date: "2008-07-18",
    genres: [{ name: "Action" }, { name: "Drama" }],
    runtime: "152",
    vote_average: 9.0,
  },
  {
    _id: "4",
    title: "Interstellar",
    backdrop_path: "/interstellar.jpg",
    release_date: "2014-11-07",
    genres: [{ name: "Sci-Fi" }, { name: "Adventure" }],
    runtime: "169",
    vote_average: 8.6,
  },
  {
    _id: "5",
    title: "The Prestige",
    backdrop_path: "/background.jpg",
    release_date: "2006-10-20",
    genres: [{ name: "Mystery" }, { name: "Drama" }],
    runtime: "130",
    vote_average: 8.5,
  },
];
